### ISSUE TITLE
Provide a more feature rich framework for server originated entity messages

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-platform#29]
[`ClientCommunicatorService.send()`](https://github.com/Terracotta-OSS/terracotta-apis/blob/master/standard-cluster-services/src/main/java/org/terracotta/entity/ClientCommunicator.java) has been deprecated as is cannot be properly supported by the platform without serious performance implications.  Entity implementors would benefit from a standard way to send a message to a client and react to a response from said client that is compatible with the overall architecture of the platform.  Create a standard implementation for server initiated request/response.

**Comment by jd0-sag** [comment]
Just to flesh out a few of the justifications as to why this was deprecated:
1. Introduces a network-blocking operation on the server.  This means that the server thread running the entity code which calls send() will block any other entity operations normally executed (potentially, in other entities) on the network response.  This makes the server's throughput sensitive to network issues but also client-side operations.
2. Complex handling of reconnect.  The same logic regarding client->server transaction re-send, on reconnect, would need to be duplicated for the server->client path.  This introduces substantial transaction tracking and ordering concerns in both the client and server, only to support this one method.
3. Failure handling in entity code.  The failure scenarios which must normally be handled by client-side user code would also be required in server-side user code, adding greater burden to the user when creating fault-tolerant entities.

Note that, while moving any kind of "response" to the client->server path will avoid these problems, there is still the case of how to handle lost messages.  That is, if the client didn't receive the message and then reconnects, do we still need some kind of server->client message tracking/acknowledgement to make the sendNoResponse() reliable or do we document it as merely "best efforts" (which introduces complexity elsewhere)?  In either case, do we need to expose anything to the server if the message fails to be delivered to the client and they never reconnect?

**Comment by jd0-sag** [comment]
After further discussions/considerations regarding this, it does seem as though the EntityAPI does provide enough information via connected/disconnected/handleReconnect that it sounds possible to implement reliable server->client messaging only using sendNoResponse() and acks sent via the client->server path.

Just as an idea, if both the server and client keep a sequence number of the sendNoResponse messages, and this is sent on reconnect, we should be able to determine if the message was lost.  It also seems as though it would be possible to avoid duplicate messages by using this same mechanism.  We couldn't do this in client->server messages since they were allowed to do too much and the platform couldn't constrain the meaning of a duplicated message after reconnect.  The server->client messages are much less powerful and there is no notion of stateful restart or fail-over, on the client side.

It means that sendNoResponse() would, indeed, be "best efforts" but we would be able to build a reliable messaging layer on top by receiving the acks on the client->server channel and accounting for client reconnect.

**Comment by jd0-sag** [comment]
Final completion of this is blocked on some API changes regarding client-side message codec.

**Comment by jd0-sag** [comment]
Blocked on:  Terracotta-OSS/terracotta-apis#14
