### ISSUE TITLE
Enforcer plugin requires we use Maven 3.2.5... thats pretty old.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-platform#460]
Can we update the enforcer plugin to either not enforce a maven version, or not enforce such an ancient one?

**Comment by henri-tremblay** [comment]
The enforcing come from the shading. Maven after this version was not taking the shaded jar as the dependency of other projects anymore.

**Comment by chrisdennis** [comment]
And we can't update maven and use an explicit older shade plugin version?

**Comment by henri-tremblay** [comment]
The problem is not the shading. It is the way maven now handles the shaded jar. Let me find the related bug.

**Comment by mathieucarbou** [comment]
Or we could just simply stop using magically-modified-shaded-artifacts... 
I am still against shading and I will always be in dependency libraries. Except if it is used on "final project".
We have to solve a lot of issues everywhere because of the fact that it has been decided to use shaded artifacts (filtering them, modifying them, enforcing rules, etc).

**Comment by chrisdennis** [comment]
I would certainly be pro someone taking on eliminating all the extra shading we do.

**Comment by henri-tremblay** [comment]
Here you go: https://issues.apache.org/jira/browse/MNG-5899

**Comment by henri-tremblay** [comment]
And yes for removing a lot of shading.

**Comment by mathieucarbou** [comment]
there is no more shading in tc-paltform.
