### ISSUE TITLE
Detach command problems for unconfigured nodes

### ISSUE THREAD

**Issue by saurabhagas** [Terracotta-OSS/terracotta-platform#656]
The new detach command UX and behavior is both confusing and wrong. The command expects the nodes to be removed to be already shut down, but the behavior is odd either way.

**Case 1: Nodes being detached are shut down**
Detach command fails with "com.terracotta.connection.api.DetailedConnectionException: java.util.concurrent.TimeoutException: localhost:9410=Connection refused".

**Case 2: Nodes being detached are not shut down**
The nodes in question should be shut down by the command upon passing `-f` option, but it doesn't happen if the nodes are not activated.

**Comment by mathieucarbou** [comment]
@saurabhagas : the new behavior is what people want. To detach a passive, the node must be shutdown first. If not, we can use -f to try force a shutdown.

Case 1: this should not happen. There is a restart delay, extly like the activate command so that the connection has tome to close and then we wait for the shutdown. How did you reproduce that ? I did a lot of system tests and not seen that

Case 2: shutdown for passive removal is only in case the node is activated. If the node is currently being configured (diagnostic mode), this is a new cluster being built so there is no nomad, no passive yet and no restart needed.

**Comment by mathieucarbou** [comment]
@saurabhagas : you might have run into this issue: https://github.com/Terracotta-OSS/terracotta-platform/pull/657

**Comment by saurabhagas** [comment]
Case 1: Two nodes in unconfigured state, attached with `attach` command. `detach` command is run after shutting down the to-be-detached node - `detach` command fails as under:

```
 1 ❯ ./tools/config-tool/bin/config-tool.sh detach -s localhost -d localhost:9510
Validating node address: localhost:9510 (this can take time if the node is not reachable)
Connecting to: localhost:9410, localhost:9510 (this can take time if some nodes are not reachable)
 - localhost:9410 is not reachable
Detaching node: localhost:9410 from stripe: localhost:9510
Sending the topology change

Error:
com.terracotta.connection.api.DetailedConnectionException: java.util.concurrent.TimeoutException: localhost:9410=Connection refused;
```

Case 2: Okay. No need to reset or shutdown here, as the topology is being built.

**Comment by mathieucarbou** [comment]
"Detach command problems for unconfigured nodes" => the behavior didn't change since months... unconfigured nodes == topology modifcation in memory, there is no nomad, no active, no passive, no working cluster. This is like attach.

The detach command has just been added with some flags to control the behavior when used at runtime.

Attach command has such flags too.

**Comment by mathieucarbou** [comment]
> Case 1: Two nodes in unconfigured state, attached with `attach` command. `detach` command is run after shutting down the to-be-detached node - `detach` command fails as under:
> 
> ```
>  1 ❯ ./tools/config-tool/bin/config-tool.sh detach -s localhost -d localhost:9510
> Validating node address: localhost:9510 (this can take time if the node is not reachable)
> Connecting to: localhost:9410, localhost:9510 (this can take time if some nodes are not reachable)
>  - localhost:9410 is not reachable
> Detaching node: localhost:9410 from stripe: localhost:9510
> Sending the topology change
> 
> Error:
> com.terracotta.connection.api.DetailedConnectionException: java.util.concurrent.TimeoutException: localhost:9410=Connection refused;
> ```
> 
> Case 2: Okay. No need to reset or shutdown here, as the topology is being built.

Your use case is invalid. 

When the nodes are unconfigured,the user is building a cluster. The nodes have node been used yet and there is no notion of working cluster, active or passive. __So the stop service and nomad system are not involved.__ The user doesn't need to stop the node because he does not need to change the HA / availability of the stripe and there is no persisted data.
 
__Reminder:__

- attach/detach commands works by updating the memory topology when nodes are unconfigured
- attach/detach commands when nodes are activated have extra checks and are using the nomad system. And considering that, there are extra options to consider like -e, -D, -W, -f.

p. 47-48 of presentation.

**Comment by mathieucarbou** [comment]
@saurabhagas : will add a commit to #657 to fix some issues
