### ISSUE TITLE
Docker support for ehcache v3.9.x

### ISSUE THREAD

**Issue by mmoayyed** [Terracotta-OSS/terracotta-platform#994]
Apoligies for cross-posting. I am not quite sure if https://github.com/Terracotta-OSS/docker is still maintained. Could someone from Terracotta-OSS take a pass at publishing a docker image for the latest server version such that it can be used for ehcache 3.9.x? 

Or, is there a version of the Terracotta server/platform in docker/contain form that could support ehcache 3.9.x? Or are there alternative ways/repos for running the server as a container, one that would be compatible with 3.9.x? 

Related issue: 
https://github.com/Terracotta-OSS/docker/issues/3

Thanks for your time!

**Comment by shane-axiom** [comment]
@mathieucarbou Could you please elaborate on why the issue was closed? Docker images not supported by this project? No time to fix? Any context would be helpful. Thank you.

**Comment by AbfrmBlr** [comment]
You can find docker images here https://hub.docker.com/r/softwareag/terracotta-server

**Comment by mathieucarbou** [comment]
@mmoayyed @shane-axiom : so this is not the right project, and also please see: https://twitter.com/alvaro_sanchez/status/1602699157109723136

@AbfrmBlr : https://hub.docker.com/r/softwareag/terracotta-server is not a replacement since the images deployed here are EE images (same as SAG Docker repo) and we cannot connect clients without a license... What they need is the equivalent of the unmaintained and unsupported Dockerfile for Ehcache kit we had in the old TC / SAG OSS repo.
